### ISSUE TITLE
Exception: docker restore failed

### ISSUE THREAD

**Issue by xiechengsheng** [xemul/p.haul#13]
Hi. I use the latest version p.haul tool to migration the number-printer docker container from one host to another, but in the destination host, in the final restore stage, an **Exception** occurred with the message: docker restore failed. 

And here is the log:
```
...
12:01:38.206: 2064: Container rootfs: /var/lib/docker/aufs/mnt/a4447ddbda3f0140d5b54f90527f523e11f884c5b1f9e0585382e6024307af2c
12:01:38.206: 2064: Container config: /var/lib/docker/containers/a4447ddbda3f0140d5b54f90527f523e11f884c5b1f9e0585382e6024307af2c
12:01:38.206: 2064: Container meta: /var/run/docker/execdriver/native/a4447ddbda3f0140d5b54f90527f523e11f884c5b1f9e0585382e6024307af2c
Traceback (most recent call last):
  File "/root/p.haul/phaul/xem_rpc.py", line 42, in work
    res = getattr(self._master, "rpc_" + data[1])(*data[2])
  File "/root/p.haul/phaul/service.py", line 120, in rpc_restore_from_images
    self.htype.final_restore(self.img, self.criu_connection)
  File "/root/p.haul/phaul/p_haul_docker.py", line 183, in final_restore
    raise Exception("docker restore failed")
Exception: docker restore failed
...
```

And when I tried to restore the destination host's container by manually, another error occurred:
```
# docker restore --image-dir=/var/local/p.haul-fs/rst-kb3qan-17.07.28-12.01/img/1  a4447ddbda3f
Error response from daemon: Cannot restore container a4447ddbda3f: [2] Container does not exist: open /var/run/docker/execdriver/native/a4447ddbda3f0140d5b54f90527f523e11f884c5b1f9e0585382e6024307af2c/state.json: no such file or directory
Error: failed to restore one or more containers
```

Here is my docker version:
```
# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59c375a
 Built:        Wed Aug 12 16:58:42 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59c375a
 Built:        Wed Aug 12 16:58:42 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

criu version:
```
# criu -V
Version: 2.2
GitID: v2.2
```

I have no idea about the solution. How to solve this bug?
Thanks in advance!

**Comment by xiechengsheng** [comment]
@xemul @boucher I saw your [demo video](https://www.youtube.com/watch?v=1lCiWaLHwxo) in youtube, but I didn't find a proper way to debug this problem.:cold_sweat:
Looking forward to your reply~

**Comment by boucher** [comment]
Are you able to use a newer version of Docker? All the latest versions of Docker have checkpoint/restore available under the experimental feature flag.

**Comment by xiechengsheng** [comment]
@boucher Thanks! One more question, does the latest version of Docker support the **live migration**? The docker container can be migrated from one machine to another **without shutdown**?

**Comment by boucher** [comment]
No. It's possible to do with some effort but its not supported directly.

**Comment by xiechengsheng** [comment]
I will update my docker version, thank you!
