### ISSUE TITLE
About live migration

### ISSUE THREAD

**Issue by 123toorc** [xemul/p.haul#16]
Hi 
      I checked this wiki "https://criu.org/Live_migration", It looks like only different of normal migration is it keep the original process in stopped status. I try to install p.haul and encounter some trouble, also it looks like nobody is maintaining it anymore.  Is it that possible I can do myself a live migration script since use criu is quite easy?  Is there any more material about how to do live migration using Criu? 

Thanks

**Comment by xemul** [comment]
@123toorc , yes, we've abandoned this project. Doing live migration "by hands" is possible, p.haul actually just scripts it, but you'll have to do many commands in shell and the final stage might be a bit suboptimal w/o any script. As far as materials is concerned -- all we have is on the wiki, the page you've found is the starting one, they're more articles it links to. If you have any specific questions -- feel free to drop me an email.

**Comment by 123toorc** [comment]
@xemul, thanks for answering me so quickly!  I checked the video of live migration of Nginx container, refer: https://asciinema.org/a/130951.  it looks straightforward. I have 2 questions;
1. Is it possible to do live migration via a TCP connection that exists?  For example, Redis migrate from A to B via connection to A. I failed to do this: "Error (soccr/soccr.c:497): Can't bind inet socket back: Cannot assign requested address", I checked an issue(2018) that mentions that criu can't restore in different IP. Is it fixable now? 
2. How to do it in Docker? Our project is to do heterogeneous migration, current we did migration by docker checkpoint. What is the extra step for live migration? I am config the tcp-established in /etc/criu/runc.conf, the Redis server did migrate successfully with an ongoing connection. But the connection with the original server still failed after the checkpoint, how to forward TCP connection to the destination? without downtime is amazing! How can I fix it?

**Comment by xemul** [comment]
1. The problem is not in criu. If you migrate to another IP all your current connections become invalid. We have an option to close all TCP stuff after migration, maybe it will work for you.

2. As far as the docker is concerned, lets ask @avagin and @adrianreber

**Comment by adrianreber** [comment]
@123toorc The most important thing is to have the same IP address. To migrate a container using Podman I have written following article: https://www.redhat.com/en/blog/container-migration-podman-rhel and there is also some documentation about Podman at https://criu.org/Podman

CRIU supports migrating TCP connections if the IP address does not change, runc also exposes it and Podman also supports `--tcp-established`. As you already said, for Docker, you can configure it via the configuration file.

The most important thing is that the IP address does not change. Without that everything you are trying to do will not work.

**Comment by 123toorc** [comment]
Thank you! @xemul  I still need to use P.haul to try live migration. When I run $ ./p.haul-service,  it asks for an RPC socket and a memory socket file descriptor.  What is it, where I can find? I'm working on the example offered here: https://github.com/checkpoint-restore/p.haul/blob/master/test/mtouch/HOWTO it doesn't say any argument needed.
Thanks, I really need some help on this, the P.haul material is not enough to understand how to fix it.  If it is possible, please I really need a HelloWorld sample.
